MassageApplication/Controllers/AdminController.cs
using MassageApplication.Database;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MassageApplication.Controllers
{
    public class AdminController : Controller
    {
        //1 is TRUE ; 0 is FALSE; 2 is nothing
        public static int result = 2;
       
        
        // GET: Admin_Stat_
        public ActionResult Index()
        {
            ViewData["booked"] = result;
            result = 2;
            return View();
        }

        
        public ActionResult updateDates()
        {
            string url = Request.UrlReferrer.AbsolutePath;

            string today = DateTime.Today.DayOfWeek.ToString().ToLower();
            string[] lastWeekDays = { "friday", "saturday", "sunday" };
            if(Array.Exists(lastWeekDays, element => element == today))
            {
                updateWeek(0);
            }
            else
            {
                updateWeek(7);
            }
            return Redirect(url);
        }


        public ActionResult dummyFunc()
        {
           return Content("Dummy");
        }

        //updates dates and times in the DB based on the time the function is called
        private void updateWeek(int plusDays = 0)
        {

            DateTime startOfWeek = DateTime.Today.AddDays(
            (int)CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek -
            (int)DateTime.Today.DayOfWeek);
            startOfWeek.AddDays(plusDays);

            string result = string.Join("," + Environment.NewLine, Enumerable
             .Range(0, 5)
             .Select(i => startOfWeek
                .AddDays(i)
                .ToString("dd-MM-yyyy")));


            IList<string> weekDays = result.Split(',').ToList();

            List<DateTime> dates = new List<DateTime>();
            foreach (var date in weekDays)
            {
                DateTime myDateTime = DateTime.Parse(date, CultureInfo.CurrentCulture,
                                     DateTimeStyles.NoCurrentDateDefault);
                dates.Add(myDateTime);
            }
            try
            {
                DataProvider.refreshWeekInDB(dates);
                AdminController.result = 1;
            }
            catch //(DbUpdateException ex)
            {
                AdminController.result = 0;
            }
        }
    }
}

MassageApplication/Controllers/CurrentScheduleController.cs
using MassageApplication.Database;
using MassageApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MassageApplication.Controllers
{
    public class CurrentScheduleController : Controller
    {
        // GET: CurrentSchedule
        public ActionResult Index()
        {

            IEnumerable<MassageInfoModel> model = DataProvider.dailyStatistics();
            return View(model);
        }


        public JsonResult changeStatusToAttended(string bookId)
        {
            DataProvider.changeAttendancyStatusToTrue(Int32.Parse(bookId));
            return Json("", JsonRequestBehavior.AllowGet);
        }

        public JsonResult changeStatusToUnAttended(string bookId)
        {
            DataProvider.changeAttendancyStatusToFalse(Int32.Parse(bookId));
            return Json("", JsonRequestBehavior.AllowGet);
        }

    }
}

MassageApplication/Controllers/EditScheduleController.cs
using MassageApplication.Database;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MassageApplication.Controllers
{
    public class EditScheduleController : Controller
    {

        // GET: EditSchedule
        public ActionResult Index()
        {
            ViewData["days"] = DataProvider.getLastWeekDays().Reverse();
            //ViewData["dict"] = DataProvider.getAvailableHours();

            return View();
        }

        public ActionResult UpdateMasseuse(int dayId, string newMasseuseName)
        {
            DataProvider.changeMasseuseName(dayId, newMasseuseName);
            return Redirect("Index"); 
        }

        public ActionResult DummyReserve(int dayId, string newMasseuseName)
        {
            DataProvider.changeMasseuseName(dayId, newMasseuseName);
            return Redirect("Index");
        }

    }
}

MassageApplication/Views/Shared/_HomeNavigation.cshtml
<div class="container">
    <nav class="navbar navbar-expand-sm navbar-light fixed-top" style="background-color: #ffdd99;">
        <a class="navbar-brand">
        <img src="https://tools4teams.nemetschek.bg/images/logos/nemetschek.svg" width="253" height="33" class="d-inline-block align-top" alt=""></a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <h6><a class="nav-link" style="color: #cc5200;" href="@Url.Action("Index","Home")">Book Massage</a></h6>
            </li>
            <li class="nav-item">
                <h6><a class="nav-link disabled" style="color: #9c3c00">|</a></h6>
            </li>
            <li class="nav-item">
                <h6><a class="nav-link" style="color: #cc5200"  href="@Url.Action("Index", "UserDailySchedule")">Daily Schedule</a> </h6>
            </li>

        </ul>
    </nav>
</div>

MassageApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/customDate.css" rel="stylesheet" />
    <link href="~/Content/AdminPage.css" rel="stylesheet" />
    <link href="~/Content/HomePage.css" rel="stylesheet" >
    
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="~/Scripts/jquery.blockUI.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <style>
        .nav-item a:hover {
            color: white !important;
            cursor: pointer;
        }
    </style>
   
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

   
</body>
</html>

MassageApplication/Views/Shared/_Navigation.cshtml
<div class="container">
    <nav class="navbar navbar-expand-sm navbar-light fixed-top" style="background-color: #ffdd99;">
        <a class="navbar-brand">
        <img src="https://tools4teams.nemetschek.bg/images/logos/nemetschek.svg" width="253" height="33" class="d-inline-block align-top" alt=""></a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <h6><a class="nav-link" style="color: #cc5200;" href="@Url.Action("Index","Admin")">Home</a></h6>
            </li>
            <li class="nav-item">
                <h6><a class="nav-link disabled" style="color: #9c3c00">|</a></h6>
            </li>
            <li class="nav-item">
                <h6><a class="nav-link" style="color: #cc5200"  href="@Url.Action("Index", "CurrentSchedule")">Current Schedule</a> </h6>
            </li>
            <li class="nav-item">
                <h6><a class="nav-link disabled" style="color: #9c3c00">|</a></h6>
            </li>
            <li class="nav-item">
                <h6><a class="nav-link" style="color: #cc5200" href="http://university2019/ReportServer/Pages/ReportViewer.aspx?%2fDailyReport&rs:Command=Render">Daily Statistics</a></h6>
            </li>
            <li class="nav-item">
                <h6><a class="nav-link disabled" style="color: #9c3c00">|</a></h6>
            </li>
            <li class="nav-item">
                <h6><a class="nav-link" style="color: #cc5200" href="http://university2019/ReportServer/Pages/ReportViewer.aspx?%2fMonthlyReport&rs:Command=Render">Monthly Statistics</a></h6>
            </li>
            <li class="nav-item">
                <h6><a class="nav-link disabled" style="color: #9c3c00">|</a></h6>
            </li>
            <li class="nav-item">
                <h6><a class="nav-link" style="color: #cc5200" href="@Url.Action("Index", "EditSchedule")">Manage Masseuses</a></h6>
            </li>

        </ul>
    </nav>
</div>